function delta_theta = compute_delta_theta(theta_1,theta_2,X,Y)
    
        delta_theta = (theta_1(1) - theta_2(1)).*X.^2 + ...
                        (theta_1(2) - theta_2(2)).*Y.^2 + ...
                          (theta_1(3) - theta_2(3)).*X.*Y + ...
                            (theta_1(4) - theta_2(4)).*X + ...
                              (theta_1(5) - theta_2(5)).*Y + ...
                                (theta_1(6) - theta_2(6)); 
    
end